### ISSUE TITLE
Q9 on R worksheet

### ISSUE THREAD

**Issue by kdwall** [Genomics-CRT/Data-Science-For-Life-Science#14]
Hi,
When I write the code:  
de_clean <- rbind(de_clean, ENSMUSG00000039287=c(570.805924, -0.4648999, 0.09045180, 2.751007e-07, 6.393878e-04))

I am getting:

Warning messages: 1: In `[<-.factor`(`*tmp*`, ri, value = 570.805924) :   invalid factor level, NA generated 2: In `[<-.factor`(`*tmp*`, ri, value = -0.4648999) :   invalid factor level, NA generated 3: In `[<-.factor`(`*tmp*`, ri, value = 0.0904518) :   invalid factor level, NA generated 4: In `[<-.factor`(`*tmp*`, ri, value = 2.751007e-07) :   invalid factor level, NA generated 5: In `[<-.factor`(`*tmp*`, ri, value = 0.0006393878) :   invalid factor level, NA generated

I would appreciate your help, thank you!

**Comment by mahoney-r** [comment]
Hi, this is most likely an class/type error with your data frame. Check the class of your columns using class() or the whole dataframe with str(). I imagine it will say they are factors, change them back to numbers with as.numeric() and it should work then.

**Comment by kdwall** [comment]
Thank you
