### ISSUE TITLE
pbmc_data.csv file NOT FOUND

### ISSUE THREAD

**Issue by JosemariCodes** [Genomics-CRT/Data-Science-For-Life-Science#16]
Hello all,
The pbmc_data.csv file necessary for starting with the R worksheet in part_3 can't be found. After running the command provided in the worksheet at the very beginning, it rises the following error(attach screenshot):

![Picture_1](https://user-images.githubusercontent.com/63736201/80948597-5bc93c80-8dea-11ea-85b5-2450ae183525.png)

**Comment by Genomics-CRT** [comment]
Should be fixed now. Thank you for the heads up.

Barry
