### ISSUE TITLE
Too many conflicts when installing rs studio 

### ISSUE THREAD

**Issue by h-ibrahim** [Genomics-CRT/Data-Science-For-Life-Science#2]
I was able to install R using the Anaconda prompt:
    conda install r-essentials
Then when I attempted to install R-studio using the command line "conda install -c r rstudio" it failed:
The solution that fixed the issue was to create a new env for that:
    conda create -n rstudio rstudio

I have Rstudio running now, but not sure if that was the correct way of doing it.
thank you

**Comment by Genomics-CRT** [comment]
Yes that's fine, R can give issues sometimes if it doesn't have its own environment. 

The main thing is that you got it up and running.
