### ISSUE TITLE
R Studio error

### ISSUE THREAD

**Issue by Guillermo1993** [Genomics-CRT/Data-Science-For-Life-Science#3]
I am having errors installing R. I tried with the command console but was having many errors, so I tried using the Anaconda Navigator, but after creating the environment this error box prompts:

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package openssl conflicts for:
python=3.8 -> openssl[version='>=1.1.1d,=1.1.1e,rstudio -> qt=5.6 -> openssl=1.0

Package vc conflicts for:
rstudio -> freetype[version='>=2.9.1'] -> vc[version='9.*|>=14.1,rstudio -> vc=14

Package vs2015_runtime conflicts for:
rstudio -> vs2015_runtime
rstudio -> vc=14 -> vs2015_runtime[version='>=14.0.25123,=14.0.25420|>=14.15.26706|>=14.16.27012']The following specifications were found to be incompatible with your CUDA driver:

- feature:/win-64::__cuda==11.0=0

Your installed CUDA driver is: 11.0

What should I do?

**Comment by Genomics-CRT** [comment]
Can you try this:
Switch to base(root) environment, create a new environment using Anaconda-navigator and select python and in the drop down box select python 3.7, also select R.

Once the environment is made go to home and click on install R-studio.

I'm thinking (hoping) it is a conflict with python version 3.8

**Comment by Guillermo1993** [comment]
Sorry for the delay, I did it and now it works perfectly, thank you very much for you help.
