### ISSUE TITLE
broken image links

### ISSUE THREAD

**Issue by JackSparrow1109** [Genomics-CRT/Data-Science-For-Life-Science#4]
Hi there, 

I tried to read the tutorial of setting up github and installing softwares, but found none of images works. For example: https://github.com/Genomics-CRT/Data-Science-For-Life Science/blob/master/Getting%20started/GitHub%20Basics.md.

Thank you.

**Comment by JackSparrow1109** [comment]
When I clicked image links, it came "404, it is not the web page you're looking for" like this:
[Page not found · GitHub.pdf](https://github.com/Genomics-CRT/Data-Science-For-Life-Science/files/4472540/Page.not.found.GitHub.pdf)

**Comment by Genomics-CRT** [comment]
Hi,

Thanks for the heads up I've made the Images repository public, all images should work now
