### ISSUE TITLE
Installing a Windows Subsystem for Linux

### ISSUE THREAD

**Issue by Emily-Purcell** [Genomics-CRT/Data-Science-For-Life-Science#6]
Hi there :) 
I am getting this error when I run: 
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux  

![error](https://user-images.githubusercontent.com/63545678/79224419-f1f4ed00-7e52-11ea-8d4d-40ce87e309c8.png)

Any suggestions?

**Comment by iseultj** [comment]
> Hi there :)
> I am getting this error when I run:
> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
> 
> ![error](https://user-images.githubusercontent.com/63545678/79224419-f1f4ed00-7e52-11ea-8d4d-40ce87e309c8.png)
> 
> Any suggestions?

Hi! There seems to be a corruption error, so I think the best way to deal with this is to run the DISM tool for windows to clean things up- If you follow the instructions here: https://support.microsoft.com/en-ie/help/947821/fix-windows-update-errors-by-using-the-dism-or-system-update-readiness .

In brief you should try to run the command DISM.exe /Online /Cleanup-image /Restorehealth as administrator; this will take a few minutes I think. 

Then type sfc /scannow and press enter.

If you have additional issues when running this, the link I pasted in should help you; If it still doesn't work, do come back to me.

**Comment by Emily-Purcell** [comment]
This worked - thank you!
