### ISSUE TITLE
Rstudio needed in anaconda...?

### ISSUE THREAD

**Issue by SaraVilla** [Genomics-CRT/Data-Science-For-Life-Science#7]
or can I use Rstudio that i have already installed directly in my PC? 
Thanks!!

**Comment by SaraVilla** [comment]
and same question for linux environment... I have Windows10, but usually work with a VirtualBox (very basic stuff)... can I continue with this for week 7 ? thanks again :)

**Comment by Genomics-CRT** [comment]
Yes that's fine! Provided the version of R isn't prehistoric. If it is and you run into trouble further down the line, you can always default back to the Anaconda install. 

Regarding the virtualbox, if you have Linux installed you should have all the basic command line utilities needed for week 7 (`awk`, `grep`, `sed`).

**Comment by SaraVilla** [comment]
perfect great! The VB has biolinux installed, so I guess it should be OK.

Thanks so much!!!
