### ISSUE TITLE
Installing R and R-Studio

### ISSUE THREAD

**Issue by Amkeav** [Genomics-CRT/Data-Science-For-Life-Science#8]
![Screenshot (Github)](https://user-images.githubusercontent.com/63410625/79463257-80eb3c00-7ff0-11ea-8db9-3d1afaebf836.png)

Hi
I keep getting this error message. 
Regards

Anna-Maria

**Comment by Genomics-CRT** [comment]
Hi,

Can you have a look at the bottom of the installing Anaconda/R document.

There is a point and click guide that should solve your problem. 
It looks like R is not installing for you correctly which means r-studio will run into problems too.

**Comment by Amkeav** [comment]
Hi
That seemed to work. says r-studio is installed. Many thanks.

Do I close or do you?
