### ISSUE TITLE
R Studio installed?

### ISSUE THREAD

**Issue by ArnoFry** [Genomics-CRT/Data-Science-For-Life-Science#9]
Hey I had troubles earlier installing R Studio via the command prompt in Anaconda, but after around 2 hours it went through. When I look in the Anaconda Navigator it still shows as _"Install_". Is there another way to find/open it or should it come up as _"Launch"_ like the other parts?
Kind regards,

![Rstudio where](https://user-images.githubusercontent.com/63790516/79465114-d9233d80-7ff2-11ea-9853-f0ff459eece1.JPG)

**Comment by Genomics-CRT** [comment]
Hi Arno, 

Unfortunately it looks like the installation was not successful. Have you attempted to install R Studio via the 'point and click' method detailed at the end of the document? 

Let us know how you progress.

**Comment by ArnoFry** [comment]
An error message came up that it couldn't install R Studio in the base (root) but needed to create a separate one. Will this create any issues going forward or should it work that way? 
Cheers

![Rstudio where](https://user-images.githubusercontent.com/63790516/79483387-2bbc2400-800a-11ea-978a-7142fc4d19c4.JPG)

**Comment by Genomics-CRT** [comment]
It will work fine (:  go ahead and install it in a new environment.
